"""dim_cnae, dim_categoria, cnae_categoria_map

Revision ID: 0ab71b50497e
Revises: df04a47294e3
Create Date: 2026-08-11 23:42:19.958749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ab71b50497e'
down_revision: Union[str, Sequence[str], None] = 'df04a47294e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dim_categoria',
    sa.Column('categoria_id', sa.Text(), nullable=False),
    sa.Column('nome', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('categoria_id'),
    schema='canonical'
    )
    op.create_table('dim_cnae',
    sa.Column('codigo_cnae', sa.Text(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('secao', sa.Text(), nullable=True),
    sa.Column('divisao', sa.Text(), nullable=True),
    sa.Column('grupo', sa.Text(), nullable=True),
    sa.Column('classe', sa.Text(), nullable=True),
    sa.Column('subclasse', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('codigo_cnae'),
    schema='canonical'
    )
    op.create_table('cnae_categoria_map',
    sa.Column('codigo_cnae', sa.Text(), nullable=False),
    sa.Column('categoria_id', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['canonical.dim_categoria.categoria_id'], ),
    sa.ForeignKeyConstraint(['codigo_cnae'], ['canonical.dim_cnae.codigo_cnae'], ),
    sa.PrimaryKeyConstraint('codigo_cnae', 'categoria_id'),
    schema='canonical'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cnae_categoria_map', schema='canonical')
    op.drop_table('dim_cnae', schema='canonical')
    op.drop_table('dim_categoria', schema='canonical')
    # ### end Alembic commands ###
