"""termometro_anuncio

Revision ID: 1cb9bccb596b
Revises: 7dbe60ef606e
Create Date: 2026-08-16 19:35:24.388078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cb9bccb596b'
down_revision: Union[str, Sequence[str], None] = '7dbe60ef606e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('termometro_anuncio',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('territorio_id', sa.Text(), nullable=True),
    sa.Column('tipologia', sa.Text(), nullable=False),
    sa.Column('operacao', sa.Text(), nullable=False),
    sa.Column('mes', sa.Date(), nullable=False),
    sa.Column('novos_anuncios', sa.Integer(), nullable=False),
    sa.Column('encerrados', sa.Integer(), nullable=False),
    sa.Column('estoque', sa.Integer(), nullable=False),
    sa.Column('novos_por_mil_domicilios', sa.Numeric(), nullable=True),
    sa.Column('rotacao_oferta', sa.Numeric(), nullable=True),
    sa.Column('renovacao', sa.Numeric(), nullable=True),
    sa.Column('permanencia_mediana_dias', sa.Numeric(), nullable=True),
    sa.Column('pressao_preco_pct_subiu', sa.Numeric(), nullable=True),
    sa.Column('pressao_preco_pct_desceu', sa.Numeric(), nullable=True),
    sa.Column('pressao_preco_variacao_mediana_pct', sa.Numeric(), nullable=True),
    sa.Column('preco_mediano', sa.Numeric(), nullable=True),
    sa.Column('preco_p25', sa.Numeric(), nullable=True),
    sa.Column('preco_p75', sa.Numeric(), nullable=True),
    sa.Column('preco_m2_mediano', sa.Numeric(), nullable=True),
    sa.Column('preco_m2_p25', sa.Numeric(), nullable=True),
    sa.Column('preco_m2_p75', sa.Numeric(), nullable=True),
    sa.Column('amostra_preco_suficiente', sa.Boolean(), nullable=False),
    sa.Column('quadrante', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['territorio_id'], ['canonical.dim_territorio.territorio_id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='analytics'
    )
    # NB: nenhum drop do índice de contagem_inicio_atividade aqui - é o
    # drift pré-existente já documentado desde o checkpoint 8 (índice
    # criado manualmente fora do Alembic), não relacionado a este
    # checkpoint. Mesmo padrão das migrações anteriores.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('termometro_anuncio', schema='analytics')
    # ### end Alembic commands ###
