"""analytics contagem_inicio_atividade

Revision ID: 3ca54ba504f1
Revises: 52bae9c35c69
Create Date: 2026-08-12 14:46:38.736851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ca54ba504f1'
down_revision: Union[str, Sequence[str], None] = '52bae9c35c69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contagem_inicio_atividade',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('territorio_id', sa.Text(), nullable=False),
    sa.Column('categoria_id', sa.Text(), nullable=True),
    sa.Column('mes', sa.Date(), nullable=False),
    sa.Column('contagem', sa.Integer(), nullable=False),
    sa.Column('calculado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['canonical.dim_categoria.categoria_id'], ),
    sa.ForeignKeyConstraint(['territorio_id'], ['canonical.dim_territorio.territorio_id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='analytics'
    )
    # ### end Alembic commands ###

    # Índice pro padrão de acesso real (indicador_repository lê por
    # bairro+mês, ou por mês pra todos os bairros de uma vez) - não
    # gerado pelo autogenerate porque não é uma constraint, é só
    # performance de leitura.
    op.create_index(
        "ix_contagem_inicio_atividade_territorio_mes",
        "contagem_inicio_atividade",
        ["territorio_id", "mes"],
        schema="analytics",
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index(
        "ix_contagem_inicio_atividade_territorio_mes",
        table_name="contagem_inicio_atividade",
        schema="analytics",
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contagem_inicio_atividade', schema='analytics')
    # ### end Alembic commands ###
