"""analytics schema, contagem_eventos

Revision ID: 52bae9c35c69
Revises: 0ab71b50497e
Create Date: 2026-08-12 00:07:13.170701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52bae9c35c69'
down_revision: Union[str, Sequence[str], None] = '0ab71b50497e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE SCHEMA IF NOT EXISTS analytics")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contagem_eventos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('territorio_id', sa.Text(), nullable=True),
    sa.Column('categoria_id', sa.Text(), nullable=True),
    sa.Column('mes', sa.Date(), nullable=False),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('contagem', sa.Integer(), nullable=False),
    sa.Column('calculado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['canonical.dim_categoria.categoria_id'], ),
    sa.ForeignKeyConstraint(['territorio_id'], ['canonical.dim_territorio.territorio_id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='analytics'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contagem_eventos', schema='analytics')
    # ### end Alembic commands ###
    op.execute("DROP SCHEMA IF EXISTS analytics")
