"""contexto_fipezap_cidade_bairro

Revision ID: 7dbe60ef606e
Revises: 95ec5cf9b2ae
Create Date: 2026-08-16 10:57:39.509213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7dbe60ef606e'
down_revision: Union[str, Sequence[str], None] = '95ec5cf9b2ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contexto_fipezap_bairro',
    sa.Column('registro_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('cidade', sa.Text(), nullable=False),
    sa.Column('operacao', sa.Text(), nullable=False),
    sa.Column('periodo_referencia', sa.Date(), nullable=False),
    sa.Column('bairro_nome', sa.Text(), nullable=False),
    sa.Column('preco_medio_m2', sa.Numeric(), nullable=False),
    sa.Column('variacao_12m', sa.Numeric(), nullable=True),
    sa.Column('territorio_id', sa.Text(), nullable=True),
    sa.Column('fonte_id', sa.Text(), nullable=False),
    sa.Column('snapshot_ref', sa.Text(), nullable=False),
    sa.CheckConstraint("operacao IN ('venda','locacao')", name='contexto_fipezap_bairro_operacao_check'),
    sa.PrimaryKeyConstraint('registro_id'),
    sa.UniqueConstraint('cidade', 'operacao', 'periodo_referencia', 'bairro_nome'),
    schema='canonical'
    )
    op.create_table('contexto_fipezap_cidade',
    sa.Column('registro_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('cidade', sa.Text(), nullable=False),
    sa.Column('operacao', sa.Text(), nullable=False),
    sa.Column('periodo_referencia', sa.Date(), nullable=False),
    sa.Column('preco_medio_m2', sa.Numeric(), nullable=False),
    sa.Column('variacao_mensal', sa.Numeric(), nullable=True),
    sa.Column('variacao_acumulada_ano', sa.Numeric(), nullable=True),
    sa.Column('variacao_12m', sa.Numeric(), nullable=True),
    sa.Column('fonte_id', sa.Text(), nullable=False),
    sa.Column('snapshot_ref', sa.Text(), nullable=False),
    sa.CheckConstraint("operacao IN ('venda','locacao')", name='contexto_fipezap_cidade_operacao_check'),
    sa.PrimaryKeyConstraint('registro_id'),
    sa.UniqueConstraint('cidade', 'operacao', 'periodo_referencia'),
    schema='canonical'
    )
    # NB: nenhum drop do índice de contagem_inicio_atividade aqui - é o
    # drift pré-existente já documentado desde o checkpoint 8 (índice
    # criado manualmente fora do Alembic), não relacionado a este
    # checkpoint. Mesmo padrão da migração anterior (95ec5cf9b2ae).
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contexto_fipezap_cidade', schema='canonical')
    op.drop_table('contexto_fipezap_bairro', schema='canonical')
    # ### end Alembic commands ###
