"""entidade e observacao_entidade

Revision ID: 905d84c028ef
Revises: 1fe6bd03d55b
Create Date: 2026-08-11 22:58:26.871279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '905d84c028ef'
down_revision: Union[str, Sequence[str], None] = '1fe6bd03d55b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entidade',
    sa.Column('entidade_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tipo_entidade', sa.Text(), nullable=False),
    sa.Column('identificador_fonte', sa.Text(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('entidade_id'),
    sa.UniqueConstraint('tipo_entidade', 'identificador_fonte'),
    schema='canonical'
    )
    op.create_table('observacao_entidade',
    sa.Column('observacao_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('entidade_id', sa.UUID(), nullable=False),
    sa.Column('observado_em', sa.Date(), nullable=False),
    sa.Column('atributos', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fonte_id', sa.Text(), nullable=False),
    sa.Column('snapshot_ref', sa.Text(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entidade_id'], ['canonical.entidade.entidade_id'], ),
    sa.PrimaryKeyConstraint('observacao_id'),
    sa.UniqueConstraint('entidade_id', 'fonte_id', 'observado_em'),
    schema='canonical'
    )
    op.alter_column('pipeline_run', 'registros_lidos',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'),
               schema='infra')
    op.alter_column('pipeline_run', 'registros_gravados',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'),
               schema='infra')
    op.alter_column('pipeline_run', 'registros_com_falha',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'),
               schema='infra')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pipeline_run', 'registros_com_falha',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'),
               schema='infra')
    op.alter_column('pipeline_run', 'registros_gravados',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'),
               schema='infra')
    op.alter_column('pipeline_run', 'registros_lidos',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'),
               schema='infra')
    op.drop_table('observacao_entidade', schema='canonical')
    op.drop_table('entidade', schema='canonical')
    # ### end Alembic commands ###
