"""observacao_anuncio, dim_tipologia_imovel, imovel_resolvido

Revision ID: 95ec5cf9b2ae
Revises: fa260fcdf01b
Create Date: 2026-08-15 21:45:52.749521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95ec5cf9b2ae'
down_revision: Union[str, Sequence[str], None] = 'fa260fcdf01b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dim_tipologia_imovel',
    sa.Column('tipologia_id', sa.Text(), nullable=False),
    sa.Column('nome', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('tipologia_id'),
    schema='canonical'
    )
    op.create_table('imovel_resolvido',
    sa.Column('cluster_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('impressao_digital', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('cluster_id'),
    schema='canonical'
    )
    op.create_table('imovel_resolvido_membro',
    sa.Column('entidade_id', sa.UUID(), nullable=False),
    sa.Column('cluster_id', sa.UUID(), nullable=False),
    sa.Column('fonte_id', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['canonical.imovel_resolvido.cluster_id'], ),
    sa.ForeignKeyConstraint(['entidade_id'], ['canonical.entidade.entidade_id'], ),
    sa.PrimaryKeyConstraint('entidade_id'),
    schema='canonical'
    )
    op.create_table('observacao_anuncio',
    sa.Column('observacao_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('entidade_id', sa.UUID(), nullable=False),
    sa.Column('observado_em', sa.Date(), nullable=False),
    sa.Column('operacao', sa.Text(), nullable=False),
    sa.Column('tipologia', sa.Text(), nullable=False),
    sa.Column('territorio_id', sa.Text(), nullable=True),
    sa.Column('preco', sa.Numeric(), nullable=True),
    sa.Column('tipo_valor', sa.Text(), server_default=sa.text("'anuncio'"), nullable=False),
    sa.Column('condominio', sa.Numeric(), nullable=True),
    sa.Column('iptu', sa.Numeric(), nullable=True),
    sa.Column('area_util_m2', sa.Numeric(), nullable=True),
    sa.Column('quartos', sa.SmallInteger(), nullable=True),
    sa.Column('banheiros', sa.SmallInteger(), nullable=True),
    sa.Column('vagas', sa.SmallInteger(), nullable=True),
    sa.Column('andar', sa.SmallInteger(), nullable=True),
    sa.Column('ofertante_hash', sa.Text(), nullable=True),
    sa.Column('impressao_digital', sa.Text(), nullable=False),
    sa.Column('fonte_id', sa.Text(), nullable=False),
    sa.Column('snapshot_ref', sa.Text(), nullable=False),
    sa.CheckConstraint("operacao IN ('venda','aluguel')", name='observacao_anuncio_operacao_check'),
    sa.CheckConstraint("tipo_valor = 'anuncio'", name='observacao_anuncio_tipo_valor_check'),
    sa.ForeignKeyConstraint(['entidade_id'], ['canonical.entidade.entidade_id'], ),
    sa.ForeignKeyConstraint(['territorio_id'], ['canonical.dim_territorio.territorio_id'], ),
    sa.ForeignKeyConstraint(['tipologia'], ['canonical.dim_tipologia_imovel.tipologia_id'], ),
    sa.PrimaryKeyConstraint('observacao_id'),
    sa.UniqueConstraint('entidade_id', 'observado_em'),
    schema='canonical'
    )
    # NB: nenhum drop do índice de contagem_inicio_atividade aqui - é o
    # drift pré-existente já documentado desde o checkpoint 8 (índice
    # criado manualmente fora do Alembic), não relacionado a este
    # checkpoint. Deixado de fora pra não misturar as duas mudanças.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('observacao_anuncio', schema='canonical')
    op.drop_table('imovel_resolvido_membro', schema='canonical')
    op.drop_table('imovel_resolvido', schema='canonical')
    op.drop_table('dim_tipologia_imovel', schema='canonical')
    # ### end Alembic commands ###
