"""fato_evento_territorial

Revision ID: df04a47294e3
Revises: 905d84c028ef
Create Date: 2026-08-11 23:17:47.371619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'df04a47294e3'
down_revision: Union[str, Sequence[str], None] = '905d84c028ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fato_evento_territorial',
    sa.Column('evento_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('entity_type', sa.Text(), nullable=False),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('entidade_id', sa.UUID(), nullable=False),
    sa.Column('territorio_id', sa.Text(), nullable=True),
    sa.Column('data_evento', sa.Date(), nullable=False),
    sa.Column('data_ingestao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('confianca', sa.Text(), nullable=False),
    sa.Column('origem_observacoes', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.CheckConstraint("confianca IN ('alta','media','baixa')", name='fato_evento_territorial_confianca_check'),
    sa.ForeignKeyConstraint(['entidade_id'], ['canonical.entidade.entidade_id'], ),
    sa.ForeignKeyConstraint(['territorio_id'], ['canonical.dim_territorio.territorio_id'], ),
    sa.PrimaryKeyConstraint('evento_id'),
    sa.UniqueConstraint('entidade_id', 'event_type', 'data_evento'),
    schema='events'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fato_evento_territorial', schema='events')
    # ### end Alembic commands ###
