"""geolocalizacao_entidade

Revision ID: dfaa8754a195
Revises: 3ca54ba504f1
Create Date: 2026-08-12 23:03:17.137331

"""
from typing import Sequence, Union

import geoalchemy2
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfaa8754a195'
down_revision: Union[str, Sequence[str], None] = '3ca54ba504f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('geolocalizacao_entidade',
    sa.Column('entidade_id', sa.UUID(), nullable=False),
    sa.Column('ponto', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('confianca', sa.Text(), nullable=False),
    sa.Column('fonte_primaria', sa.Text(), nullable=False),
    sa.Column('fonte_secundaria', sa.Text(), nullable=True),
    sa.Column('precisao_geocodebr', sa.Text(), nullable=True),
    sa.Column('distancia_desempate_m', sa.Numeric(), nullable=True),
    sa.Column('geocodificado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revisado_em', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("confianca IN ('alta','media','baixa')", name='geolocalizacao_entidade_confianca_check'),
    sa.ForeignKeyConstraint(['entidade_id'], ['canonical.entidade.entidade_id'], ),
    sa.PrimaryKeyConstraint('entidade_id'),
    schema='canonical'
    )
    # NB: nenhum op.create_index explícito para 'ponto' - geoalchemy2 cria
    # o índice GIST espacial automaticamente logo após o CREATE TABLE
    # (mesmo padrão de dim_territorio.geometria); um op.create_index aqui
    # colide com esse índice autogerado (DuplicateTable).
    #
    # NB: autogenerate também detectou 'ix_contagem_inicio_atividade_territorio_mes'
    # como removido - isso é drift do checkpoint 8 (índice criado fora do
    # Alembic), não relacionado a esta migração. Omitido de propósito;
    # não é objeto deste checkpoint.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('geolocalizacao_entidade', schema='canonical')
    # ### end Alembic commands ###
