"""contexto_bcb_quintoandar_censo

Revision ID: fa260fcdf01b
Revises: 19b351ae137c
Create Date: 2026-08-15 16:46:42.970104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa260fcdf01b'
down_revision: Union[str, Sequence[str], None] = '19b351ae137c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contexto_bcb_imobiliario',
    sa.Column('registro_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('uf', sa.Text(), nullable=False),
    sa.Column('periodo_referencia', sa.Date(), nullable=False),
    sa.Column('indicador', sa.Text(), nullable=False),
    sa.Column('categoria', sa.Text(), nullable=False),
    sa.Column('tipo_valor', sa.Text(), nullable=True),
    sa.Column('unidade', sa.Text(), nullable=False),
    sa.Column('leitura', sa.Numeric(), nullable=False),
    sa.Column('fonte_id', sa.Text(), nullable=False),
    sa.Column('snapshot_ref', sa.Text(), nullable=False),
    sa.CheckConstraint("categoria IN ('valor','area','contagem')", name='contexto_bcb_imobiliario_categoria_check'),
    sa.CheckConstraint("tipo_valor IS NULL OR tipo_valor IN ('venal','avaliacao','anuncio','transacao')", name='contexto_bcb_imobiliario_tipo_valor_check'),
    sa.PrimaryKeyConstraint('registro_id'),
    sa.UniqueConstraint('uf', 'periodo_referencia', 'indicador'),
    schema='canonical'
    )
    op.create_table('contexto_quintoandar_aluguel',
    sa.Column('registro_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('cidade', sa.Text(), nullable=False),
    sa.Column('periodo_referencia', sa.Date(), nullable=False),
    sa.Column('segmento', sa.Text(), nullable=False),
    sa.Column('aluguel_m2', sa.Numeric(), nullable=False),
    sa.Column('variacao_mensal', sa.Numeric(), nullable=True),
    sa.Column('variacao_12m', sa.Numeric(), nullable=True),
    sa.Column('fonte_id', sa.Text(), nullable=False),
    sa.Column('snapshot_ref', sa.Text(), nullable=False),
    sa.CheckConstraint("segmento IN ('cidade_toda','1_dormitorio','2_dormitorios','3_dormitorios')", name='contexto_quintoandar_aluguel_segmento_check'),
    sa.PrimaryKeyConstraint('registro_id'),
    sa.UniqueConstraint('cidade', 'periodo_referencia', 'segmento'),
    schema='canonical'
    )
    op.create_table('contexto_censo_setor',
    sa.Column('setor_censitario', sa.Text(), nullable=False),
    sa.Column('territorio_id', sa.Text(), nullable=True),
    sa.Column('municipio_codigo', sa.Text(), nullable=False),
    sa.Column('area_km2', sa.Numeric(), nullable=False),
    sa.Column('populacao_total', sa.Integer(), nullable=False),
    sa.Column('domicilios_total', sa.Integer(), nullable=False),
    sa.Column('domicilios_particulares_ocupados', sa.Integer(), nullable=False),
    sa.Column('domicilios_particulares_vagos', sa.Integer(), nullable=False),
    sa.Column('ano_referencia', sa.Integer(), nullable=False),
    sa.Column('fonte_id', sa.Text(), nullable=False),
    sa.Column('snapshot_ref', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['territorio_id'], ['canonical.dim_territorio.territorio_id'], ),
    sa.PrimaryKeyConstraint('setor_censitario'),
    schema='canonical'
    )
    # NB: um 'op.drop_index' para ix_contagem_inicio_atividade_territorio_mes
    # foi gerado aqui pelo autogenerate - é o drift pré-existente já
    # documentado desde o checkpoint 8 (índice criado explicitamente na
    # migração original, nunca declarado no modelo ORM), não relacionado a
    # este checkpoint. Removido desta migração de propósito.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contexto_censo_setor', schema='canonical')
    op.drop_table('contexto_quintoandar_aluguel', schema='canonical')
    op.drop_table('contexto_bcb_imobiliario', schema='canonical')
    # ### end Alembic commands ###
